services:
  app:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./scripts:/app/scripts
      - ./requirements.txt:/app/requirements.txt
    tty:
      true
